// Generated by https://quicktype.io

export interface Jardin {
    ok:       boolean;
    total:    number;
    usuarios: Usuario[];
}

export interface Usuario {
    _id:       string;
    ciudad:    string;
    rol:       string;
    estado:    boolean;
    google:    boolean;
    nombre:    string;
    apellido:  string;
    correo:    string;
    direccion: string;
    jardinero: Jardinero;
}

export interface Jardinero {
    _id:          string;
    estado:       boolean;
    activo:       boolean;
    usuario:      User;
    especialidad: string;
    descripcion:  string;
}

interface User {
    _id:          string;
    nombre:    string;
    apellido:  string;
    correo:    string;

}